<?php


function sackreuter_menu_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'menu_edit_item':
      if($form['mlid']['#value']) {
        $anchor = variable_get($form['mlid']['#value'] . '_anchor', '');
      }else {
        $anchor = '';
      }

      $form['link_menu_anchor'] = array(
        '#type' => 'textfield',
        '#title' => t('Anchor'),
        '#default_value' => $anchor,
        '#size' => 60,
        '#maxlength' => 128,
      );

      //Add custom submit
      array_unshift($form['#submit'], '_sackreuter_menu_form_submit');

      break;
  }
}


function _sackreuter_menu_form_submit($form, &$form_state) {
  $variable_name = $form_state['values']['mlid'] . '_anchor';
  $variable = variable_get($variable_name);
  if (!empty($form_state['values']['link_menu_anchor'])) {
    variable_set($variable_name, $form_state['values']['link_menu_anchor']);
  }
  elseif (isset($variable)) {
    variable_del($variable_name);
  }
}